Convert to BusIO
adafruit/Adafruit_CCS811 pull request #30
Opened 2021-08-10 18:00 UTC by caternuson

For #29. Converts to BusIO with no change to existing library API *except* added a `TwoWire` parameter to `begin()`, but sets a default so should be backwards compatible.

Tested on Qt PY with `CCS811_test` example sketch from library.
![Screenshot from 2021-08-10 10-59-35](https://user-images.githubusercontent.com/8755041/128911018-731a0034-455b-41b7-8976-382f32f832c3.png)

2021-08-10 18:03 UTC, ladyada requested changes

2021-08-10 18:03 UTC, ladyada commented on Adafruit_CCS811.cpp
> -  Wire.setClockStretchLimit(500);
we'll still need to do this i think?

2021-08-10 18:03 UTC, ladyada commented on Adafruit_CCS811.cpp
> +  } else {
do we want to put this into busio? its now 3 times we have to 'reimplement' it?

2021-08-10 18:18 UTC, caternuson commented on Adafruit_CCS811.cpp
> +  } else {
ha! guess we had the same thought. ok...you saw issue over in busio. yep!

2021-08-11 15:24 UTC, caternuson commented
@ladyada This hasn't been merged yet. I can also remove chunkificaiton as part of this PR to sync with busio?

2021-08-11 15:25 UTC, ladyada commented
yah i think best to do that just so you can retest real fast

2021-08-11 15:49 UTC, ladyada requested changes

2021-08-13 17:08 UTC, ladyada approved these changes

2021-08-13 17:09 UTC, merged